services:
  - type: web
    name: coaching-erp
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn coaching_erp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        fromDatabase:
          name: coaching-erp-db
          property: connectionString

databases:
  - name: coaching-erp-db
    plan: free
