# Generated by Django 5.2.13 on 2026-05-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0015_delete_studentmonthexemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('guardian', 'Guardian numbers'), ('student', 'Student numbers'), ('both', 'Student and guardian numbers')], default='guardian', max_length=20)),
                ('active_students_only', models.BooleanField(default=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchNoticeRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('recipient_label', models.CharField(max_length=20)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.client')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='coaching.batchnotice')),
            ],
            options={
                'ordering': ['client__roll', 'client__name', 'recipient_label'],
            },
        ),
    ]
