# Generated by Django 5.2.13 on 2026-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0016_batchnotice_batchnoticerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchnoticerecipient',
            name='gateway_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchnoticerecipient',
            name='gateway_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
